/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 14 09:42:01 GMT 2018
 */

package sg.edu.sutd.bank.webapp.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sg.edu.sutd.bank.webapp.model.UserRole;
import sg.edu.sutd.bank.webapp.service.UserRoleDAOImpl;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UserRoleDAOImpl_ESTest extends UserRoleDAOImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UserRoleDAOImpl userRoleDAOImpl0 = new UserRoleDAOImpl();
      UserRole userRole0 = new UserRole();
      try { 
        userRoleDAOImpl0.create(userRole0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // java.lang.ClassNotFoundException: Class 'com/mysql/jdbc/Driver.class' should be in target project, but could not be found!
         //
         verifyException("sg.edu.sutd.bank.webapp.commons.ServiceException", e);
      }
  }
}
